filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#   username: '${ELASTICSEARCH_USERNAME:}'
#   password: '${ELASTICSEARCH_PASSWORD:}'

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/ed-cloud/logs/audit/*.log
  fields:
    docType: audit-log
    project: ed-cloud
output.logstash:
  # Boolean flag to enable or disable the output module.
  #enabled: true

  # The Logstash hosts
  hosts: ["logstash:5044"]
  bulk_max_size: 2048
